### ISSUE TITLE
Add support for task groups

### ISSUE THREAD

**Issue by eblondel** [fdiwg/dcf-shiny#155]
_DRAFT SPECIFICATIONS_

The _dcf-shiny_ app should be enhanced with the management of task / working groups:

**User management**
- [ ] groups will be defined in the same way as roles, with a key/value pairs defined in the app configuration
- [ ] the DB model users table should be extended to manage a column to store the list of groups which the user belongs to
- [ ] the users entry form (edition/update) should be extended to support the addition of one or more groups to the user

**Task management**
- [ ] Need to extend task definition by adding group(s).

**Privileges/capabilities** (given to a group member)
- [ ] Data submission (validation & upload): A user that is member of a group will be able to select a task that is associated to this group. If not a group member, he/she will not see the a group task for selection.
- [ ] Data view: A user that is member of a group should be able to see submissions of a group. QUID if they have to go through regional data manager validation
